// @import "tw-animate-css";

import './globals.css'
import { Inter } from 'next/font/google'
import React from "react"
// import { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import localFont from "next/font/local";

import Navbar from '../components/Navbar'

import { Orbitron } from "next/font/google";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700"],
});
// const inter = Inter({ subsets: ['latin'] })
// const _geist = Geist({ subsets: ["latin"] })
// const _geistMono = Geist_Mono({ subsets: ["latin"] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   icons: {
//     icon: [
//       {
//         url: "/icon-light-32x32.png",
//         media: "(prefers-color-scheme: light)",
//       },
//       {
//         url: "/icon-dark-32x32.png",
//         media: "(prefers-color-scheme: dark)",
//       },
//       {
//         url: "/icon.svg",
//         type: "image/svg+xml",
//       },
//     ],
//     apple: "/apple-icon.png",
//   },
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      {/* <body className={`${inter.className} bg-[#0D0F1A]`}> */}
      <body className={`${orbitron.className}`}>
        <Navbar />
        <main className="">
          {children}
        </main>
      </body>
    </html>
  )
}
